name: Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please provide details below.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Broken links
        - Code examples not working
        - Typo/grammar error
        - Outdated information
        - Suggestion for improvement
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where did you find this issue?
      placeholder: |
        - File: README.md, docs/api.md, etc.
        - Section: Getting Started, API Reference, etc.
        - URL: https://...
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the current documentation say? (if applicable)
      placeholder: Current documentation content...

  - type: textarea
    id: expected
    attributes:
      label: Expected Content
      description: What should the documentation say instead?
      placeholder: Suggested improvement...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Use Case/Context
      description: How were you using the documentation when you found this issue?
      placeholder: I was trying to...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help fix this documentation issue

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue
      placeholder: Additional details...